In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan,4],
                  'B':[5,np.nan,np.nan,8],
                  'C':[10,20,30,40]})

In [ ]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [ ]:
df.fillna(df.mean())

          A    B   C
0  1.000000  5.0  10
1  2.000000  6.5  20
2  2.333333  6.5  30
3  4.000000  8.0  40

In [ ]:
# Strategy 2 remove data
df.dropna(axis= 1, thresh = 3)

     A   C
0  1.0  10
1  2.0  20
2  NaN  30
3  4.0  40

In [ ]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [ ]:
df.dtypes

A    float64
B    float64
C      int64
dtype: object

In [ ]:
#Staregy 3: Fill in data 
df.fillna(value = 'FILL VALUE')

            A           B   C
0         1.0         5.0  10
1         2.0  FILL VALUE  20
2  FILL VALUE  FILL VALUE  30
3         4.0         8.0  40

In [ ]:
df.fillna(value = 0)

     A    B   C
0  1.0  5.0  10
1  2.0  0.0  20
2  0.0  0.0  30
3  4.0  8.0  40

In [ ]:
df['A'] = df['A'].fillna(value=0)

In [ ]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  0.0  NaN  30
3  4.0  8.0  40

In [ ]:
df['B'].fillna(value = df['B'].mean())

0    5.0
1    6.5
2    6.5
3    8.0
Name: B, dtype: float64

In [ ]:
df.fillna(df.mean())

     A    B   C
0  1.0  5.0  10
1  2.0  6.5  20
2  0.0  6.5  30
3  4.0  8.0  40